language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t ctinni/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true ctinni/docker-react npm run test -- -- coverage
  